language: generic
branches:
  only:
    - master
cache:
  directories:
    - vendor
services:
  - docker
sudo: required
install:
  - make bootstrap
script:
  - DEIS_REGISTRY='' make test build docker-build
