# A debugging utility for testing Minio from within k8s.
apiVersion: v1
kind: Pod
metadata:
  name: deis-mc
  labels:
    heritage: deis
    version: 2015-sept
spec:
  restartPolicy: Never
  containers:
    - name: mc
      imagePullPolicy: Always
      image: smothiki/minio:v2
      command:
        - mc
      args:
        - "mode memory limit 512MB"
