apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-minio
  labels:
    heritage: deis
    release: 2.0.0-alpha
spec:
  replicas: 1
  selector:
    app: deis-minio
  template:
    metadata:
      labels:
        app: deis-minio
    spec:
      containers:
        - imagePullPolicy: IfNotPresent
          name: deis-minio
          image: quay.io/deis/minio:2.0.0-alpha
          ports:
            - containerPort: 9000
          command:
            - boot
          args:
            # not running with ssl yet
            # - "--cert=/var/run/secrets/deis/minio/ssl/access-cert"
            # - "--key=/var/run/secrets/deis/minio/ssl/access-pem"
            - "server"
            - "/home/minio/"
          volumeMounts:
            - name: minio-admin
              mountPath: /var/run/secrets/deis/minio/admin
              readOnly: true
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
            # - name: minio-ssl
            #   mountPath: /var/run/secrets/deis/minio/ssl
            #   readOnly: true
      volumes:
        - name: minio-admin
          secret:
            secretName: minio-admin
        - name: minio-user
          secret:
            secretName: minio-user
        # - name: minio-ssl
        #   secret:
        #     secretName: minio-ssl
